# # Este workflow construirá y desplegará una aplicación Node.js a un Azure Web App cuando se haga un commit a la rama principal.
#
# Este workflow asume que ya has creado el servicio de Azure App Service web app.
# Para instrucciones ve a https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# Para configurar este workflow:
#
# 1. Descarga el Publish Profile para tu Azure Web App. Puedes descargar este archivo desde la página de Overview de tu Web App en el Azure Portal.
#    Para más información: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Crea un secreto en tu repositorio llamado AZURE_WEBAPP_PUBLISH_PROFILE, pega el contenido del perfil de publicación como valor del secreto.
#    Para instrucciones sobre cómo obtener el perfil de publicación ve a: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Cambia el valor de AZURE_WEBAPP_NAME. Opcionalmente, cambia los valores de AZURE_WEBAPP_PACKAGE_PATH y NODE_VERSION.
#
# Para más información sobre GitHub Actions para Azure: https://github.com/Azure/Actions
# Para más información sobre la acción de despliegue a Azure Web Apps: https://github.com/Azure/webapps-deploy
# Para más ejemplos de workflows de GitHub Actions para desplegar en Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: The-fucking-Peaky-Blinders    # Cambia esto al nombre de tu aplicación en Azure
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # Cambia esto a la ruta de tu proyecto web, por defecto es la raíz del repositorio
  NODE_VERSION: '14.x'                # Cambia esto a la versión de Node.js que usas

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
